spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_atendance_n8
    password: ${database_pwd}
    username: ${database_user}
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
    #  use-new-id-generator-mappings: false
    #  ddl-auto: update